language: node_js
node_js:
    - "node"
    - "6"
    - "5"
    - "4"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
    directories:
        - typings
        - node_modules